---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver
    apt:
      name: apache2
      state: absent
      
  - name: install git on ansible nodes
    apt:
      name: git
      state: present 
  - name: i want to install webserver 
    apt:
       name: "{{mywebpackonubuntu}}"
       state: present
    when: ansible_os_family== "Debian"
